AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spot Analyzer - Lambda with Public Function URL

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment

Globals:
  Function:
    Timeout: 240
    MemorySize: 256

Resources:
  # CloudWatch Log Group for Lambda function
  SpotAnalyzerLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/spot-analyzer-${Environment}
      RetentionInDays: 3  # Logs expire after 3 days (adjust as needed: 1, 3, 5, 7, 14, 30, 60, 90, etc.)

  SpotAnalyzerFunction:
    Type: AWS::Serverless::Function
    DependsOn: SpotAnalyzerLogGroup
    Properties:
      FunctionName: !Sub spot-analyzer-${Environment}
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: cmd/lambda
      Timeout: 240
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          UI_VERSION: "v2"  # v1 = classic, v2 = modern UI
          AZURE_SECRET_NAME: "spot-analyzer/azure-credentials"  # AWS Secrets Manager secret name
          GCP_SECRET_NAME: "spot-analyzer/gcp-credentials"      # AWS Secrets Manager secret name for GCP
      # Reference the log group we created
      LoggingConfig:
        LogGroup: !Ref SpotAnalyzerLogGroup
      # Enable Lambda Function URL with public access (no IAM auth)
      # Note: CORS is handled in the Lambda code, not here (to avoid validation issues)
      FunctionUrlConfig:
        AuthType: NONE
      # IAM policies for the Lambda to access AWS services
      Policies:
        - Version: '2012-10-17'
          Statement:
            # EC2 Spot Instance permissions
            - Effect: Allow
              Action:
                - ec2:DescribeSpotPriceHistory
                - ec2:DescribeInstanceTypes
                - ec2:DescribeAvailabilityZones
                - ec2:DescribeRegions
              Resource: "*"
            # Secrets Manager for Azure and GCP credentials
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
              Resource:
                - !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:spot-analyzer/*"
                - !Sub "arn:aws:secretsmanager:us-east-1:${AWS::AccountId}:secret:spot-analyzer/*"
    Metadata:
      BuildMethod: go1.x

Outputs:
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt SpotAnalyzerFunction.Arn
  
  FunctionUrl:
    Description: Lambda Function URL (Public Endpoint)
    Value: !GetAtt SpotAnalyzerFunctionUrl.FunctionUrl
    Export:
      Name: !Sub ${AWS::StackName}-FunctionUrl
  
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref SpotAnalyzerFunction

  LogGroupName:
    Description: CloudWatch Log Group Name
    Value: !Ref SpotAnalyzerLogGroup

  LogGroupArn:
    Description: CloudWatch Log Group ARN
    Value: !GetAtt SpotAnalyzerLogGroup.Arn
