AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Spot Analyzer - Lambda with Public Function URL

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
    Description: Deployment environment

Globals:
  Function:
    Timeout: 60
    MemorySize: 256

Resources:
  SpotAnalyzerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub spot-analyzer-${Environment}
      Handler: bootstrap
      Runtime: provided.al2023
      CodeUri: cmd/lambda
      Timeout: 60
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
      # Enable Lambda Function URL with public access (no IAM auth)
      # Note: CORS is handled in the Lambda code, not here (to avoid validation issues)
      FunctionUrlConfig:
        AuthType: NONE
      # IAM policies for the Lambda to access AWS services
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - ec2:DescribeSpotPriceHistory
                - ec2:DescribeInstanceTypes
                - ec2:DescribeAvailabilityZones
              Resource: "*"
    Metadata:
      BuildMethod: go1.x

Outputs:
  FunctionArn:
    Description: Lambda Function ARN
    Value: !GetAtt SpotAnalyzerFunction.Arn
  
  FunctionUrl:
    Description: Lambda Function URL (Public Endpoint)
    Value: !GetAtt SpotAnalyzerFunctionUrl.FunctionUrl
    Export:
      Name: !Sub ${AWS::StackName}-FunctionUrl
  
  FunctionName:
    Description: Lambda Function Name
    Value: !Ref SpotAnalyzerFunction
